---

- name: Restart bind9
  service:
    name: bind9
    state: restarted

- name: Reload bind9
  service:
    name: bind9
    state: reloaded

- name: Restart monit
  service:
    name: monit
    state: restarted

- name: Zone file change
  debug:
    msg: "dummy handler"
